Check for /run/ mistral on service start and create with right permissions if missing.
Fixes #254, currently WIP.

diff --git a/packages/st2mistral/debian/mistral-server.init b/packages/st2mistral/debian/mistral-server.init
--- a/packages/st2mistral/debian/mistral-server.init
+++ b/packages/st2mistral/debian/mistral-server.init
@@ -21,7 +21,8 @@ NAME=mistral-server
 DAEMON=/opt/stackstorm/mistral/bin/$NAME
 COMPONENTS="api,engine,executor"
 SERVER_ARGS="--config-file /etc/mistral/mistral.conf --log-file /var/log/mistral/mistral-server.log"
-PIDFILE=/var/run/mistral/$NAME.pid
+RUN_DIR="/run/mistral"
+PIDFILE="${RUN_DIR}/$NAME.pid"
 SCRIPTNAME=/etc/init.d/$NAME
 RUNAS_USER="mistral"
 RUNAS_GROUP="mistral"
@@ -67,6 +68,19 @@ do_start()
   #   1 if daemon was already running
   #   2 if daemon could not be started
   lsb_running && return 1
+
+  # /run is a tmpfs mount, so we need to check the directory exists and create.
+  # Otherwise the service will not start following a reboot.
+  if [ ! -d "$RUN_DIR" ] ; then
+      if ! mkdir -p "$RUN_DIR" ; then
+          log_failure_msg "can't create $RUN_DIR"
+          exit 1
+      fi
+      if ! chown mistral:mistral "$RUN_DIR" ; then
+          log_warning_msg "can't chown $RUN_DIR"
+      fi
+  fi
+
   start-stop-daemon --start --quiet --chuid $RUNAS_USER:$RUNAS_GROUP --umask $UMASK --background --make-pidfile --pidfile $PIDFILE \
     --exec $DAEMON -- $DAEMON_ARGS \
     || return 2
